// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_apksig

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Info about a single X.509 certificate in an APK signer's chain.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CertificateInfo (
  /** Subject distinguished name (e.g. "CN=Android Debug, O=Android, C=US"). */
  val subjectDn: String,
  /** Issuer distinguished name. */
  val issuerDn: String,
  /** Certificate serial number (decimal string). */
  val serialNumber: String,
  /**
   * SHA-256 fingerprint of the DER-encoded certificate (hex, upper-case,
   * colon-separated, e.g. "AA:BB:CC:…").
   */
  val sha256Fingerprint: String,
  /** Certificate validity start: milliseconds since Unix epoch. */
  val validFromMs: Long,
  /** Certificate validity end: milliseconds since Unix epoch. */
  val validUntilMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CertificateInfo {
      val subjectDn = pigeonVar_list[0] as String
      val issuerDn = pigeonVar_list[1] as String
      val serialNumber = pigeonVar_list[2] as String
      val sha256Fingerprint = pigeonVar_list[3] as String
      val validFromMs = pigeonVar_list[4] as Long
      val validUntilMs = pigeonVar_list[5] as Long
      return CertificateInfo(subjectDn, issuerDn, serialNumber, sha256Fingerprint, validFromMs, validUntilMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      subjectDn,
      issuerDn,
      serialNumber,
      sha256Fingerprint,
      validFromMs,
      validUntilMs,
    )
  }
}

/**
 * Info about one signer in an APK's signature block.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ApkSignerInfo (
  /** Certificate chain for this signer (index 0 is the signing certificate). */
  val certificates: List<CertificateInfo?>,
  val hasV1Signature: Boolean,
  val hasV2Signature: Boolean,
  val hasV3Signature: Boolean,
  val hasV4Signature: Boolean,
  /** Human-readable error messages for this signer. */
  val errors: List<String?>,
  /** Human-readable warning messages for this signer. */
  val warnings: List<String?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApkSignerInfo {
      val certificates = pigeonVar_list[0] as List<CertificateInfo?>
      val hasV1Signature = pigeonVar_list[1] as Boolean
      val hasV2Signature = pigeonVar_list[2] as Boolean
      val hasV3Signature = pigeonVar_list[3] as Boolean
      val hasV4Signature = pigeonVar_list[4] as Boolean
      val errors = pigeonVar_list[5] as List<String?>
      val warnings = pigeonVar_list[6] as List<String?>
      return ApkSignerInfo(certificates, hasV1Signature, hasV2Signature, hasV3Signature, hasV4Signature, errors, warnings)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      certificates,
      hasV1Signature,
      hasV2Signature,
      hasV3Signature,
      hasV4Signature,
      errors,
      warnings,
    )
  }
}

/**
 * The result of verifying an APK's signatures.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ApkVerifyResult (
  /** Whether the APK's signatures are valid. */
  val verified: Boolean,
  /** Per-signer information. */
  val signers: List<ApkSignerInfo?>,
  /** Top-level verification errors (not tied to a specific signer). */
  val errors: List<String?>,
  /** Top-level warnings. */
  val warnings: List<String?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApkVerifyResult {
      val verified = pigeonVar_list[0] as Boolean
      val signers = pigeonVar_list[1] as List<ApkSignerInfo?>
      val errors = pigeonVar_list[2] as List<String?>
      val warnings = pigeonVar_list[3] as List<String?>
      return ApkVerifyResult(verified, signers, errors, warnings)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      verified,
      signers,
      errors,
      warnings,
    )
  }
}

/**
 * Parameters for signing an APK with a Java keystore (.jks / .p12).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ApkSignRequest (
  /** Absolute path to the unsigned (or previously signed) input APK. */
  val inputApkPath: String,
  /**
   * Absolute path where the signed APK should be written.
   * May be the same as [inputApkPath] (in-place signing).
   */
  val outputApkPath: String,
  /** Absolute path to the keystore file (.jks or .p12). */
  val keystorePath: String,
  /** Password for the keystore. */
  val keystorePassword: String,
  /** Alias of the key entry inside the keystore. */
  val keyAlias: String,
  /** Password for the private key (may be the same as [keystorePassword]). */
  val keyPassword: String,
  /** Enable JAR signing (v1). Defaults to the apksig library default when null. */
  val v1SigningEnabled: Boolean? = null,
  /** Enable APK Signature Scheme v2. Defaults to the library default when null. */
  val v2SigningEnabled: Boolean? = null,
  /** Enable APK Signature Scheme v3. Defaults to the library default when null. */
  val v3SigningEnabled: Boolean? = null,
  /** Enable APK Signature Scheme v4. Defaults to the library default when null. */
  val v4SigningEnabled: Boolean? = null,
  /**
   * Minimum Android SDK version the signed APK must support.
   * Influences which signature schemes are applied.
   */
  val minSdkVersion: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApkSignRequest {
      val inputApkPath = pigeonVar_list[0] as String
      val outputApkPath = pigeonVar_list[1] as String
      val keystorePath = pigeonVar_list[2] as String
      val keystorePassword = pigeonVar_list[3] as String
      val keyAlias = pigeonVar_list[4] as String
      val keyPassword = pigeonVar_list[5] as String
      val v1SigningEnabled = pigeonVar_list[6] as Boolean?
      val v2SigningEnabled = pigeonVar_list[7] as Boolean?
      val v3SigningEnabled = pigeonVar_list[8] as Boolean?
      val v4SigningEnabled = pigeonVar_list[9] as Boolean?
      val minSdkVersion = pigeonVar_list[10] as Long?
      return ApkSignRequest(inputApkPath, outputApkPath, keystorePath, keystorePassword, keyAlias, keyPassword, v1SigningEnabled, v2SigningEnabled, v3SigningEnabled, v4SigningEnabled, minSdkVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      inputApkPath,
      outputApkPath,
      keystorePath,
      keystorePassword,
      keyAlias,
      keyPassword,
      v1SigningEnabled,
      v2SigningEnabled,
      v3SigningEnabled,
      v4SigningEnabled,
      minSdkVersion,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CertificateInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApkSignerInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApkVerifyResult.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApkSignRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CertificateInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ApkSignerInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ApkVerifyResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ApkSignRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ApksigHostApi {
  /**
   * Verifies the signatures of the APK at [apkPath].
   *
   * [minSdkVersion] and [maxSdkVersion] bound the range of Android API
   * levels the verification should target; pass null to use the defaults
   * derived from the APK's manifest.
   */
  fun verifyApk(apkPath: String, minSdkVersion: Long?, maxSdkVersion: Long?, callback: (Result<ApkVerifyResult>) -> Unit)
  /**
   * Signs [request.inputApkPath] and writes the result to
   * [request.outputApkPath].
   *
   * Throws a [PlatformException] on any signing error (I/O, bad keystore,
   * invalid key, etc.).
   */
  fun signApk(request: ApkSignRequest, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by ApksigHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ApksigHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ApksigHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_apksig.ApksigHostApi.verifyApk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apkPathArg = args[0] as String
            val minSdkVersionArg = args[1] as Long?
            val maxSdkVersionArg = args[2] as Long?
            api.verifyApk(apkPathArg, minSdkVersionArg, maxSdkVersionArg) { result: Result<ApkVerifyResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_apksig.ApksigHostApi.signApk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ApkSignRequest
            api.signApk(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
