// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Info about a single X.509 certificate in an APK signer's chain.
class CertificateInfo {
  CertificateInfo({
    required this.subjectDn,
    required this.issuerDn,
    required this.serialNumber,
    required this.sha256Fingerprint,
    required this.validFromMs,
    required this.validUntilMs,
  });

  /// Subject distinguished name (e.g. "CN=Android Debug, O=Android, C=US").
  String subjectDn;

  /// Issuer distinguished name.
  String issuerDn;

  /// Certificate serial number (decimal string).
  String serialNumber;

  /// SHA-256 fingerprint of the DER-encoded certificate (hex, upper-case,
  /// colon-separated, e.g. "AA:BB:CC:…").
  String sha256Fingerprint;

  /// Certificate validity start: milliseconds since Unix epoch.
  int validFromMs;

  /// Certificate validity end: milliseconds since Unix epoch.
  int validUntilMs;

  Object encode() {
    return <Object?>[
      subjectDn,
      issuerDn,
      serialNumber,
      sha256Fingerprint,
      validFromMs,
      validUntilMs,
    ];
  }

  static CertificateInfo decode(Object result) {
    result as List<Object?>;
    return CertificateInfo(
      subjectDn: result[0]! as String,
      issuerDn: result[1]! as String,
      serialNumber: result[2]! as String,
      sha256Fingerprint: result[3]! as String,
      validFromMs: result[4]! as int,
      validUntilMs: result[5]! as int,
    );
  }
}

/// Info about one signer in an APK's signature block.
class ApkSignerInfo {
  ApkSignerInfo({
    required this.certificates,
    required this.hasV1Signature,
    required this.hasV2Signature,
    required this.hasV3Signature,
    required this.hasV4Signature,
    required this.errors,
    required this.warnings,
  });

  /// Certificate chain for this signer (index 0 is the signing certificate).
  List<CertificateInfo?> certificates;

  bool hasV1Signature;

  bool hasV2Signature;

  bool hasV3Signature;

  bool hasV4Signature;

  /// Human-readable error messages for this signer.
  List<String?> errors;

  /// Human-readable warning messages for this signer.
  List<String?> warnings;

  Object encode() {
    return <Object?>[
      certificates,
      hasV1Signature,
      hasV2Signature,
      hasV3Signature,
      hasV4Signature,
      errors,
      warnings,
    ];
  }

  static ApkSignerInfo decode(Object result) {
    result as List<Object?>;
    return ApkSignerInfo(
      certificates: (result[0] as List<Object?>?)!.cast<CertificateInfo?>(),
      hasV1Signature: result[1]! as bool,
      hasV2Signature: result[2]! as bool,
      hasV3Signature: result[3]! as bool,
      hasV4Signature: result[4]! as bool,
      errors: (result[5] as List<Object?>?)!.cast<String?>(),
      warnings: (result[6] as List<Object?>?)!.cast<String?>(),
    );
  }
}

/// The result of verifying an APK's signatures.
class ApkVerifyResult {
  ApkVerifyResult({
    required this.verified,
    required this.signers,
    required this.errors,
    required this.warnings,
  });

  /// Whether the APK's signatures are valid.
  bool verified;

  /// Per-signer information.
  List<ApkSignerInfo?> signers;

  /// Top-level verification errors (not tied to a specific signer).
  List<String?> errors;

  /// Top-level warnings.
  List<String?> warnings;

  Object encode() {
    return <Object?>[verified, signers, errors, warnings];
  }

  static ApkVerifyResult decode(Object result) {
    result as List<Object?>;
    return ApkVerifyResult(
      verified: result[0]! as bool,
      signers: (result[1] as List<Object?>?)!.cast<ApkSignerInfo?>(),
      errors: (result[2] as List<Object?>?)!.cast<String?>(),
      warnings: (result[3] as List<Object?>?)!.cast<String?>(),
    );
  }
}

/// Parameters for signing an APK with a Java keystore (.jks / .p12).
class ApkSignRequest {
  ApkSignRequest({
    required this.inputApkPath,
    required this.outputApkPath,
    required this.keystorePath,
    required this.keystorePassword,
    required this.keyAlias,
    required this.keyPassword,
    this.v1SigningEnabled,
    this.v2SigningEnabled,
    this.v3SigningEnabled,
    this.v4SigningEnabled,
    this.minSdkVersion,
  });

  /// Absolute path to the unsigned (or previously signed) input APK.
  String inputApkPath;

  /// Absolute path where the signed APK should be written.
  /// May be the same as [inputApkPath] (in-place signing).
  String outputApkPath;

  /// Absolute path to the keystore file (.jks or .p12).
  String keystorePath;

  /// Password for the keystore.
  String keystorePassword;

  /// Alias of the key entry inside the keystore.
  String keyAlias;

  /// Password for the private key (may be the same as [keystorePassword]).
  String keyPassword;

  /// Enable JAR signing (v1). Defaults to the apksig library default when null.
  bool? v1SigningEnabled;

  /// Enable APK Signature Scheme v2. Defaults to the library default when null.
  bool? v2SigningEnabled;

  /// Enable APK Signature Scheme v3. Defaults to the library default when null.
  bool? v3SigningEnabled;

  /// Enable APK Signature Scheme v4. Defaults to the library default when null.
  bool? v4SigningEnabled;

  /// Minimum Android SDK version the signed APK must support.
  /// Influences which signature schemes are applied.
  int? minSdkVersion;

  Object encode() {
    return <Object?>[
      inputApkPath,
      outputApkPath,
      keystorePath,
      keystorePassword,
      keyAlias,
      keyPassword,
      v1SigningEnabled,
      v2SigningEnabled,
      v3SigningEnabled,
      v4SigningEnabled,
      minSdkVersion,
    ];
  }

  static ApkSignRequest decode(Object result) {
    result as List<Object?>;
    return ApkSignRequest(
      inputApkPath: result[0]! as String,
      outputApkPath: result[1]! as String,
      keystorePath: result[2]! as String,
      keystorePassword: result[3]! as String,
      keyAlias: result[4]! as String,
      keyPassword: result[5]! as String,
      v1SigningEnabled: result[6] as bool?,
      v2SigningEnabled: result[7] as bool?,
      v3SigningEnabled: result[8] as bool?,
      v4SigningEnabled: result[9] as bool?,
      minSdkVersion: result[10] as int?,
    );
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CertificateInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is ApkSignerInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ApkVerifyResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is ApkSignRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CertificateInfo.decode(readValue(buffer)!);
      case 130:
        return ApkSignerInfo.decode(readValue(buffer)!);
      case 131:
        return ApkVerifyResult.decode(readValue(buffer)!);
      case 132:
        return ApkSignRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ApksigHostApi {
  /// Constructor for [ApksigHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ApksigHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Verifies the signatures of the APK at [apkPath].
  ///
  /// [minSdkVersion] and [maxSdkVersion] bound the range of Android API
  /// levels the verification should target; pass null to use the defaults
  /// derived from the APK's manifest.
  Future<ApkVerifyResult> verifyApk(
    String apkPath,
    int? minSdkVersion,
    int? maxSdkVersion,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_apksig.ApksigHostApi.verifyApk$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[
              apkPath,
              minSdkVersion,
              maxSdkVersion,
            ])
            as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ApkVerifyResult?)!;
    }
  }

  /// Signs [request.inputApkPath] and writes the result to
  /// [request.outputApkPath].
  ///
  /// Throws a [PlatformException] on any signing error (I/O, bad keystore,
  /// invalid key, etc.).
  Future<void> signApk(ApkSignRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_apksig.ApksigHostApi.signApk$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
